version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: noir_postgres
    environment:
      POSTGRES_USER: noir_admin
      POSTGRES_PASSWORD: noir_super_password
      POSTGRES_DB: noir_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: